osx_image: xcode7.2
language: objective-c
script: 
  - xctool -project AdvancedCollectionView.xcodeproj -scheme AdvancedCollectionView build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
